gig/urls.py
from django.urls import include, path
from .views import campaign

urlpatterns = [
	path(
		"campaign/",
		include(
			[
				path('', campaign.campaign_list, name='CampaignList'),
				path('write/', campaign.campaign_write, name='CampaignWrite'),
				path('delete/<int:campaign_id>/', campaign.campaign_delete, name='CampaignDelete'),
				path('update/<int:campaign_id>/', campaign.campaign_update, name='CampaignUpdate'),
				path('<int:campaign_id>/', campaign.campaign_detail, name='CampaignDetail'),
				path('favorite/', campaign.campaign_favorite, name='CampaignFavorite'),
				path('offer/<int:campaign_id>/', campaign.campaign_offer, name='CampaignOffer'),
				path('pick/<int:campaign_id>/', campaign.campaign_pick, name='CampaignPick'),
				path('review/<int:campaign_id>/', campaign.campaign_review, name='CampaignReview'),
				path('confirm/<int:review_id>/', campaign.campaign_confirm, name='CampaignConfirm'),
			]
		)
	),
]

gig/models.py
from django.db import models
from django.conf import settings
from datetime import datetime
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from account.models import UserShippingAddress


def upload_to(instance, filename):
	nowDate = datetime.now().strftime("%Y/%m/%d")
	return '/'.join([str(instance.user.id), instance.folder , nowDate, filename])

class GigCampaign(models.Model):
	user = models.ForeignKey(
				settings.AUTH_USER_MODEL,
				on_delete=models.CASCADE
	)
	subject = models.CharField(max_length=255)
	keyword = models.CharField(max_length=255)
	product_url = models.CharField(max_length=255,blank=True)
	provide = models.CharField(max_length=255)
	guide_line = models.TextField()
	limit_offer = models.IntegerField()
	reward = models.IntegerField(default=0)
	category = models.CharField(max_length=255)
	campaign_type = models.CharField(max_length=255)
	channel = models.CharField(max_length=255)
	address = models.CharField(max_length=255)
	finished_at = models.DateTimeField()
	started_at = models.DateTimeField(default=datetime.now)
	merchant_uid = models.CharField(max_length=255, null=True)
	is_paid=models.BooleanField(default=False)
	is_item=models.BooleanField(default=False)

	is_recommend=models.BooleanField(default=False)
	favorite_user = models.ManyToManyField(
				settings.AUTH_USER_MODEL,
				related_name="favorite_user_set",
				blank=True,
				through='GigCampaignFavorite'
	)
	offer_user = models.ManyToManyField(
				settings.AUTH_USER_MODEL,
				related_name="offer_user_set",
				blank=True,
				through='GigCampaignOffer'
	)
	folder = 'campaign'
	thumbnail = ProcessedImageField(
				upload_to=upload_to,
				processors=[ResizeToFill(500, 500)],
	)


	class Meta:
		managed = True
		db_table = 'gig_campaign'


class GigCampaignFavorite(models.Model):
	user = models.ForeignKey(
			settings.AUTH_USER_MODEL,
			on_delete=models.CASCADE
	)
	campaign = models.ForeignKey(
			GigCampaign,
			on_delete=models.CASCADE
	)
	favorite_at = models.DateTimeField(default=datetime.now)


	class Meta:
		managed = True
		db_table = 'gig_campaign_favorite'


class GigCampaignOffer(models.Model):
	user = models.ForeignKey(
			settings.AUTH_USER_MODEL,
			on_delete=models.CASCADE
	)
	campaign = models.ForeignKey(
			GigCampaign,
			on_delete=models.CASCADE
	)
	appeal = models.CharField(max_length=255)
	sns_url = models.CharField(max_length=255)
	shipping_address = models.ForeignKey(
			UserShippingAddress,
			on_delete=models.CASCADE
	)
	offer_at = models.DateTimeField(default=datetime.now)
	is_picked=models.BooleanField(default=False)

	class Meta:
		managed = True
		db_table = 'gig_campaign_offer'


class GigCampaignReview(models.Model):
	offer = models.ForeignKey(
			GigCampaignOffer,
			on_delete=models.CASCADE
	)
	review_url = models.CharField(max_length=255)
	created_at = models.DateTimeField(default=datetime.now)
	is_confirm = models.BooleanField(default=False)

	class Meta:
		managed = True
		db_table = 'gig_campaign_review'

gig/views/campaign.py
from django.shortcuts import redirect, render,get_object_or_404
from django.http import JsonResponse
from django.db.models import Q
from gig.models import GigCampaign,GigCampaignOffer,GigCampaignReview
from django.core.paginator import Paginator
from account.views import user_login
from main.views import index
from datetime import datetime, timedelta
import random
import re
from util.views import AddUserPointLog
from payment.views import payment_refund
from account.models import UserShippingAddress


def campaign_list(request):
	seo = {
		'title': "콘디",
	}
	

	category_list = [
		'코스메틱', 
		'미용', 
		'패션/잡화',
		'식품', 
		'생활용품', 
		'출산/육아', 
		'디지털/가전', 
		'스포츠/건강', 
		'반려동물', 
		'맛집', 
		'여행/숙박', 
		'지역/문화', 
		'기타'
	]
	channel_list = ["네이버블로그", "인스타그램", "유튜브", "카페", "네이버포스트", "기타"]
	type_list = ['배송형', '방문형', '기자단','구매형']
	
	q = Q()
	q &= Q(is_paid = True)
	if request.GET.get("category"):
		q &= Q(category = category_list[int(request.GET.get("category"))])
	if request.GET.get("channel"):
		q &= Q(channel = channel_list[int(request.GET.get("channel"))])
	if request.GET.get("type"):
		q &= Q(campaign_type = type_list[int(request.GET.get("type"))])
	if request.GET.get("keyword"):
		q &= Q(subject__icontains = request.GET.get("keyword"))
	
	

	campaign_list =  GigCampaign.objects.filter(q).order_by('-is_item', "-id")
	page        = int(request.GET.get('p', 1))
	pagenator   = Paginator(campaign_list, 10)
	campaign_list = pagenator.get_page(page)
	return render(request, 'gig/campaign/campaign_list.html' ,{
		"seo":seo,
		"campaign_list":campaign_list,
		"category_list":category_list,
		"channel_list":channel_list,
		"type_list":type_list,
	})


def campaign_write(request):
	if not request.user.is_authenticated: #로그인 상태면
		return redirect(user_login)

	if request.method == 'POST':
		campaign_type = request.POST.get("campaign_type")
		category = request.POST.get("category")
		thumbnail = request.FILES['campaign_img']
		subject = request.POST.get("subject")
		provide = request.POST.get("provide")
		guide_line = request.POST.get("guide_line")
		keyword = request.POST.get("keyword")
		product_url = request.POST.get("product_url")
		channel = request.POST.get("channel")
		limit_offer = request.POST.get("limit_offer")
		finished_at = request.POST.get("finished_at")
		item = request.POST.get("item")
		reward = re.sub(r'[^0-9]', '', request.POST.get('reward'))

			
		try:
			campaign = GigCampaign()
			campaign.campaign_type = campaign_type
			campaign.category = category
			campaign.subject = subject
			campaign.channel = channel
			campaign.thumbnail = thumbnail
			campaign.provide = provide
			campaign.guide_line = guide_line
			campaign.keyword = keyword
			campaign.product_url = product_url
			campaign.limit_offer = limit_offer
			campaign.finished_at = datetime.now() + timedelta(days=int(finished_at))
			campaign.reward = reward
			campaign.user = request.user
			campaign.merchant_uid = None
			if item != 'default':
				campaign.is_item = True
				if item == 'recommend':
					campaign.is_recommend = True
			campaign.save()

			campaign = GigCampaign.objects.get(pk=campaign.pk)
			campaign.merchant_uid = str(datetime.now().strftime('%Y%m%d')) + str(campaign.pk) + str(random.randint(10000,99999))
			campaign.save()


			result = '200'
			result_text = campaign.merchant_uid
		except:
			result = '201'
			result_text = '알수없는 오류입니다. 다시시도 해주세요.'
		

		result = {'result': result, 'result_text': result_text}
		return JsonResponse(result)
	else:
		return render(request, 'gig/campaign/campaign_write.html')


def campaign_update(request, campaign_id):
	try:
		campaign = GigCampaign.objects.get(pk=campaign_id, user=request.user)
	except:
		return redirect(user_login)

	if request.method == 'POST':
		campaign_type = request.POST.get("campaign_type")
		category = request.POST.get("category")
		try:
			thumbnail = request.FILES['campaign_img']
		except:
			thumbnail = None
		subject = request.POST.get("subject")
		provide = request.POST.get("provide")
		guide_line = request.POST.get("guide_line")
		keyword = request.POST.get("keyword")
		product_url = request.POST.get("product_url")
		channel = request.POST.get("channel")
			
		try:
			campaign.campaign_type = campaign_type
			campaign.category = category
			campaign.subject = subject
			campaign.channel = channel
			if thumbnail is not None:
				campaign.thumbnail = thumbnail
			campaign.provide = provide
			campaign.guide_line = guide_line
			campaign.keyword = keyword
			campaign.product_url = product_url
			campaign.save()
			result = '200'
			result_text = '수정이 완료되었습니다.'
		except:
			result = '201'
			result_text = '알수없는 오류입니다. 다시시도 해주세요.'
		print(result_text)

		result = {'result': result, 'result_text': result_text}
		return JsonResponse(result)
	else:
		return render(request, 'gig/campaign/campaign_update.html', {"campaign_update":campaign})


def campaign_detail(request, campaign_id):
	try:
		campaign = GigCampaign.objects.get(pk=campaign_id)
	except:
		return redirect('/')

	try:
		campaign_offer = GigCampaignOffer.objects.get(campaign=campaign_id, user=request.user)
	except:
		campaign_offer = None
	print(campaign_offer)
	
	q = Q()
	q &= Q(is_paid = True)
	q &= Q(is_item = True)
	q &= Q(is_recommend = True)
	q &= Q(finished_at__gte=datetime.now())
	recommend_campaign_list =  GigCampaign.objects.filter(q).order_by("-id")

	return render(request, 'gig/campaign/campaign_detail.html', {"campaign_detail":campaign, "campaign_offer":campaign_offer, "recommend_campaign_list":recommend_campaign_list})


def campaign_delete(request, campaign_id):
	try:
		campaign = GigCampaign.objects.get(pk=campaign_id, user=request.user)
	except:
		campaign = None

	if campaign is not None:
		if payment_refund(campaign.merchant_uid,'캠페인 환불 요청'):
			campaign.delete()
			result = '200'
			result_text = '삭제가 완료되었습니다.'
		else:
			result = '201'
			result_text = '알수없는 오류입니다. 다시시도 해주세요.'
	else:
		result = '201'
		result_text = '알수없는 오류입니다. 다시시도 해주세요.'

	result = {'result': result, 'result_text': result_text}
	return JsonResponse(result)


def campaign_offer(request,campaign_id):
	if not request.user.is_authenticated: #로그인 상태면
		return redirect(user_login)
	
	if request.method == 'POST':
		shipping_address_id = request.POST.get("shipping_address")
		appeal = request.POST.get("appeal")
		sns_url = request.POST.get("sns_url")

		try:
			shipping_address = UserShippingAddress.objects.get(pk=shipping_address_id)
		except:
			shipping_address = None

		try:
			campaign = GigCampaign.objects.get(pk=campaign_id)
		except:
			campaign = None

		if campaign is not None:
			if request.user in campaign.offer_user.all():
				campaign.offer_user.remove(request.user)
				result = '200'
				result_text = "캠페인 신청 취소가 완료되었습니다."
			else:
				if shipping_address is not None:
					campaign_offer = GigCampaignOffer()
					campaign_offer.campaign = campaign
					campaign_offer.user = request.user
					campaign_offer.shipping_address = shipping_address
					campaign_offer.appeal = appeal
					campaign_offer.sns_url = sns_url
					campaign_offer.save()

					result = '200'
					result_text = "캠페인 신청이 완료되었습니다."
				else:
					result = '201'
					result_text = '알수없는 오류입니다. 다시시도 해주세요.'
		else:
			result = '201'
			result_text = '알수없는 오류입니다. 다시시도 해주세요.'

		result = {'result': result, 'result_text': result_text}
		return JsonResponse(result)
	else:
		return redirect(index)
	


def campaign_favorite(request):
	if not request.user.is_authenticated: #로그인 상태면
		result = '201'
		result_text = '로그인이 필요합니다.'
		
		result = {'result': result, 'result_text': result_text}
		return JsonResponse(result)   
	if request.method == 'POST':
		try:
			campaign = GigCampaign.objects.get(id=request.POST.get("campaign_id"))
		except:
			campaign = None

		
		if campaign is not None:
			if request.user in campaign.favorite_user.all():
				campaign.favorite_user.remove(request.user)
				result = '200'
				result_text = False #좋아요 삭제
			else:
				campaign.favorite_user.add(request.user)
				result = '200'
				result_text = True #좋아요 추가
		else:
			result = '201'
			result_text = '알수없는 오류입니다. 다시시도 해주세요.'
		
	else:
		result = '201'
		result_text = '알수없는 오류입니다. 다시시도 해주세요.'
	result = {'result': result, 'result_text': result_text}
	return JsonResponse(result)


def campaign_pick(request, campaign_id):
	if not request.user.is_authenticated: #로그인 상태면
		return redirect(user_login)

	q = Q()
	q &= Q(campaign_id = campaign_id)
	campaign_offer_list = GigCampaignOffer.objects.filter(q).order_by("-is_picked","-id")
	q &= Q(is_picked = True)
	campaign_picked_count = GigCampaignOffer.objects.filter(q).count()

	try:
		is_mine = campaign_offer_list[0].campaign.user
	except:
		is_mine = None

	if is_mine != request.user:
		return redirect(index)

	if request.method == 'POST':
		offer_id = request.POST.get("offer_id")

		try:
			campaign_offer = GigCampaignOffer.objects.get(id=offer_id)
		except:
			campaign_offer = None
		
		if campaign_offer is not None:
			try:
				campaign_offer.is_picked = True
				campaign_offer.save()
				result = '200'
				result_text = '체험단 선정이 완료되었습니다.'
			except:
				result = '201'
				result_text = '알수없는 오류입니다. 다시시도 해주세요.'
		else:
			result = '201'
			result_text = '알수없는 오류입니다. 다시시도 해주세요.'

		result = {'result': result, 'result_text': result_text}
		return JsonResponse(result)
	else:
		return render(request, 'gig/campaign/campaign_pick.html',{"campaign_offer_list":campaign_offer_list,"campaign_picked_count":campaign_picked_count})
	

def campaign_review(request,campaign_id):
	if not request.user.is_authenticated: #로그인 상태면
		return redirect(user_login)

	try:
		campaign_offer = GigCampaignOffer.objects.get(user=request.user,campaign=campaign_id,is_picked=True)
	except:
		campaign_offer = None
	
	if campaign_offer is not None:
		review_url = request.POST.get("review_url")
		try:
			campaign_review = GigCampaignReview()
			campaign_review.offer = campaign_offer
			campaign_review.review_url = review_url
			campaign_review.save()
			result = '200'

templates/gig/campaign/campaign_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load humanize %}

<section class="py-4 border-bottom border-gray-100 sticky-lg-top sticky-lg-top-header bg-body z-index-8">
	<div class="container">
		<form>
			<div class="row g-2">
				<div class="col-12 col-md-12 col-lg-2 align-self-center">
					<h6 class="m-0">Filter By</h6>
				</div>

				<div class="col-6 col-md-3 col-lg-2">
					<select class="px-nice-select" name="category">
						<option value="" data-display="카테고리">카테고리</option>
						{% for categoryList in category_list %}
						<option value="{{forloop.counter0}}">{{categoryList}}</option>
						{% endfor %}
					</select>
				</div>
				<div class="col-6 col-md-3 col-lg-2">
					<select class="px-nice-select" name="channel">
						<option value="" data-display="활동 채널">활동 채널</option>
						{% for channelList in channel_list %}
						<option value="{{forloop.counter0}}">{{channelList}}</option>
						{% endfor %}
					</select>
				</div>
				<div class="col-6 col-md-3 col-lg-2">
					<select class="px-nice-select" name="type">
						<option value="" data-display="캠페인 타입">캠페인 타입</option>
						{% for typeList in type_list %}
						<option value="{{forloop.counter0}}">{{typeList}}</option>
						{% endfor %}
					</select>
				</div>

				<div class="col-6 col-md-3 col-lg-2">
					<input type="text" name="keyword" class="form-control" placeholder="캠페인 검색">
				</div>
				
				<div class="col-6 col-md-3 col-lg-2 d-flex justify-content-center">
					<a href="{% url 'CampaignList' %}" class="btn btn-outline-primary mx-1 w-100">초기화</a>
					<button type="submit" class="btn btn-primary w-100 mx-1">검색</button>
				</div>
			</div>
		</form>
	</div>
</section>


<section class="py-5 py-lg-8">
	<div class="container">
		<div class="row mb-7 gy-4">

			{% for campaignList in campaign_list %}
			<div class="col-md-4 col-sm-6 col-lg-3">
					<div class="product-card">
							<div class="product-card-img-box">
									<a href="{% url 'CampaignDetail' campaignList.id %}">
											<img class="product-card-img" src="{{campaignList.thumbnail.url}}" title="" alt="">
									</a>
							</div>
							<div class="product-card-body">
									<div class="product-title mb-3">

										{% if campaignList.channel == '네이버블로그' %}
										<span class="badge bg-naver">{{campaignList.channel}}</span>
										{% elif campaignList.channel == '인스타그램' %}
										<span class="badge bg-insta">{{campaignList.channel}}</span>
										{% elif campaignList.channel == '유튜브' %}
										<span class="badge bg-youtube">{{campaignList.channel}}</span>
										{% elif campaignList.channel == '카페' %}
										<span class="badge bg-cafe">{{campaignList.channel}}</span>
										{% elif campaignList.channel == '네이버포스트' %}
										<span class="badge bg-post">{{campaignList.channel}}</span>
										{% else %}
										<span class="badge bg-primary">{{campaignList.channel}}</span>
										{% endif %}

										<span class="badge bg-light text-muted">{{campaignList.campaign_type}}</span>
										<h6 class="m-0">
												<a class="text-reset stretched-linka" href="{% url 'CampaignDetail' campaignList.id %}">{{campaignList.subject}}</a>
										</h6>
										<span class="small">{{campaignList.provide}}</span>
									</div>
									<div class="product-actions d-flex align-items-end">
											<div class="price">
													<h6 class="m-0">신청 {{campaignList.offer_user.all.count}}명<span class="text-body fw-400">/{{campaignList.limit_offer}}명</span> </h6>
											</div>
											<div class="like ms-auto">
													<a href="#" onclick="campaign_favorite_submit(this);" data-campaign-id="{{campaignList.id}}" class="d-flex lh-1 fw-500 text-reset">
														{% if request.user in campaignList.favorite_user.all %}
															<i class="bi bi-heart-fill me-1 text-danger"></i>
														{% else %}
															<i class="bi bi-heart me-1"></i>
														{% endif %}
															<small>{{campaignList.favorite_user.all.count}}</small>
													</a>
											</div>
									</div>
									<div class="product-footer">
										<span class="badge bg-info">New</span>
										{% if campaignList.reward != 0 %}
										<span class="badge border text-dark">+{{campaignList.reward|intcomma}}P</span>
										{% endif %}
									</div>
							</div>
					</div>
			</div>
			{% endfor %}
		</div>

		<div class="mb-5">
			<ul class="pagination justify-content-center m-0">
				{% if campaign_list.has_previous %}
				<li class="page-item ">
					<a class="page-link" href="?p={{campaign_list.previous_page_number }}">이전</a>
				</li>
				{% else %}
				<li class="page-item disabled">
					<span class="page-link">이전</span>
				</li>
				{% endif %}

				{% for page_number in campaign_list.paginator.page_range %}
					{% if page_number >= campaign_list.number|add:-2 and page_number <= campaign_list.number|add:2 %}
						{% if page_number == campaign_list.number %}
						<li class="page-item active">
							<span class="page-link">{{ page_number }}</span>
						</li>
						{% else %}
						<li class="page-item">
								<a class="page-link" href="?p={{page_number }}">{{ page_number }}</a>
						</li>
						{% endif %}
					{% endif %}
				{% endfor %}

				{% if campaign_list.has_next  %}
				<li class="page-item">
					<a class="page-link" href="?p={{campaign_list.next_page_number }}">다음</a> 
				</li>
				{% else %}
				<li class="page-item disabled">
					<span class="page-link">다음</span>
				</li>
				{% endif %}
			</ul>
		</div>
	</div>
</section>


<script>
	$(document).ready(function() {
		let campaign_category = get_parameter("category");
		let campaign_channel = get_parameter("channel");
		let campaign_type = get_parameter("type");
		let campaign_keyword = get_parameter("keyword");
		
		if (!isEmpty(campaign_category)) {
			$("select[name=category]").val(campaign_category).prop("selected", true);
		}
		if (!isEmpty(campaign_channel)) {
			$("select[name=channel]").val(campaign_channel).prop("selected", true);
		}
		if (!isEmpty(campaign_type)) {
			$("select[name=type]").val(campaign_type).prop("selected", true);
		}
		if (!isEmpty(campaign_keyword)) {
			$("input[name=keyword]").val(campaign_keyword);
		}
  });

	function get_parameter(name) {
    name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
    var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
        results = regex.exec(location.search);
    return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
	}

	function campaign_favorite_submit(e) {
		let favorite_i_tag = e.children[0];
		let favorite_smaill_tag = e.children[1];
    $.ajax({
        type : 'POST',
        url : "{% url 'CampaignFavorite' %}",
				headers: { "X-CSRFToken": '{{csrf_token}}' },
        data : {
					campaign_id: $(e).attr('data-campaign-id'),
				},
        dataType : 'json',
        success: function(data){
          if(data.result==200){
            if (data.result_text) {
							favorite_i_tag.className = '';
							favorite_i_tag.classList.add('bi', 'bi-heart-fill', 'me-1', 'text-danger');
							favorite_smaill_tag.innerText = Number(favorite_smaill_tag.innerText)+1
						} else {
							favorite_i_tag.className = '';
							favorite_i_tag.classList.add('bi', 'bi-heart', 'me-1');
							favorite_smaill_tag.innerText = Number(favorite_smaill_tag.innerText)-1
						}
          }else{
            openPopup("알림", data.result_text);
          }
          return;
        },
        error: function (request, status, error){
          var msg = "ERROR : " + request.status + "<br>"
			    msg +=  + "내용 : " + request.responseText + "<br>" + error;
			    console.log(msg);
        }
    });
  }
</script>
{% endblock %}

templates/gig/campaign/campaign_pick.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load campaign_filter %}

<section class="section position-relative">
	<div class="container">
			<div class="row justify-content-center section-heading">
					<div class="col-lg-6 text-center">
							<h5 class="h1">신청 체험단 리스트</h5>
							<h6 class="m-0">선정 {{campaign_picked_count}}명<span class="text-body fw-400">/{{campaign_offer_list.0.campaign.limit_offer}}명</span> </h6>
					</div>
			</div>
			<div class="row g-3">
				{% for campaignOfferList in campaign_offer_list %}
				<div class="col-lg-3 col-sm-6">
						<div class="card position-relative">
								<div class="card-body">
										<div class="d-flex align-items-center">
											<div class="avatar">
												<img title="" alt="" class="avatar-img rounded-circle" src="{{campaignOfferList.user.avater.url}}">
											</div>
											<div class="col ps-3">
													<h6 class="m-0">{{campaignOfferList.user.nickname}}</h6>
						
											</div>
											{% if campaignOfferList.is_picked %}
											<div class="ms-auto">
												<p class="icon-sm bg-primary text-white rounded-circle" href="#">
														<i class="bi bi-check"></i>
												</p>
											</div>
											{% endif %}
										</div>
										<p class="mt-1 small">{{campaignOfferList.appeal}}</p>
										<div class="border-top border-gray-100 mt-3 pt-3 row gx-2">
												{% if campaignOfferList.is_picked %}
													{% if campaignOfferList.gigcampaignreview_set.all.0.review_url %}
													<div class="col-6">
														<a class="btn w-100 btn-primary-soft" target="_blank" href="{{campaignOfferList.gigcampaignreview_set.all.0.review_url}}">리뷰보기</a>
													</div>
													{% if campaignOfferList.gigcampaignreview_set.all.0.is_confirm %}
													<div class="col-6">
														<a class="btn w-100 btn-primary disabled" href="#">완료</a>
													</div>
													{% else %}
													<div class="col-6">
														<a class="btn w-100 btn-primary" href="#" onclick="campaign_confirm_submit(this);" data-url="{% url 'CampaignConfirm' campaignOfferList.gigcampaignreview_set.all.0.id %}">완료</a>
													</div>
													{% endif %}
													{% else %}
													<div class="col-12">
														<a class="btn w-100 btn-primary-soft disabled" href="#">리뷰작성 대기중</a>
													</div>
													{% endif %}
												{% else %}
												<div class="col-6">
													<a class="btn w-100 btn-primary-soft" href="{{campaignOfferList.sns_url}}">SNS보기</a>
												</div>
												<div class="col-6">
													<a class="btn w-100 btn-primary" href="#" onclick="campaign_pick_submit('{{campaignOfferList.id}}');">선정하기</a>
												</div>
												{% endif %}
										</div>
								</div>
						</div>
				</div>
				{% endfor %}
			</div>
			<div class="pt-6 text-center">
				<a class="btn btn-primary-soft" href="{% url 'CampaignDetail' campaign_offer_list.0.campaign.id %}">
					캠페인 바로가기
				</a>
			</div>
	</div>
</section>

<script>
	function campaign_pick_submit(e) {

$.ajax({
		type : 'POST',
		url : "{{request.path}}",
		headers: { "X-CSRFToken": '{{csrf_token}}' },
		data : {
			offer_id: e,
		},
		dataType : 'json',
		success: function(data){
			if(data.result==200){
				if (data.result_text) {
					openPopup("알림", data.result_text,'',"reload");
				} else {
					openPopup("알림", data.result_text,);
				}
				return
			}else{
				openPopup("알림", data.result_text);
			}
			return;
		},
		error: function (request, status, error){
			var msg = "ERROR : " + request.status + "<br>"
			msg +=  + "내용 : " + request.responseText + "<br>" + error;
			console.log(msg);
		}
});
}

	function campaign_confirm_submit(e) {

		$.ajax({
				type : 'GET',
				url : e.dataset.url,
				headers: { "X-CSRFToken": '{{csrf_token}}' },
				dataType : 'json',
				success: function(data){
					if(data.result==200){
						if (data.result_text) {
							openPopup("알림", data.result_text,'',"reload");
						} else {
							openPopup("알림", data.result_text,);
						}
						return
					}else{
						openPopup("알림", data.result_text);
					}
					return;
				},
				error: function (request, status, error){
					var msg = "ERROR : " + request.status + "<br>"
					msg +=  + "내용 : " + request.responseText + "<br>" + error;
					console.log(msg);
				}
		});
	}
</script>
{% endblock %}